export const arrayToRender = {
    items: [
        {
            img: './img/white.jpg',
            article: 'Номер 1',
            text: 'Постільна білизна біла',
            sizeL : 'L',
            sizeM : 'M',
            sizeS : 'S',
            priceL : 100,
            priceM: 50,
            priceS: 10,
            type : 'products'
        },
        {
            img: './img/white.jpg',
            article: 'Номер 2',
            text: 'Постільна білизна біла',
            sizeL : 'L',
            sizeM : 'M',
            sizeS : 'S',
            priceL : 100,
            priceM: 50,
            priceS: 10,
            type : 'products'
        },
        {
            img: './img/white.jpg',
            article: 'Номер 3',
            text: 'Постільна білизна біла',
            sizeL : 'L',
            sizeM : 'M',
            sizeS : 'S',
            priceL : 100,
            priceM: 50,
            priceS: 10, 
            type : 'products'
        },
        {
            img: './img/purple.jpg',
            article: 'Номер 4',
            text: 'Постільна білизна фіолетова',
            sizeL : 'L',
            sizeM : 'M',
            sizeS : 'S',
            priceL : 100,
            priceM: 50,
            priceS: 10 ,
            type : 'set'
        },
        {
            img: './img/purple.jpg',
            article: 'Номер 1',
            text: 'Постільна білизна фіолетова',
            sizeL : 'L',
            sizeM : 'M',
            sizeS : 'S',
            priceL : 100,
            priceM: 50,
            priceS: 10 ,
            type : 'set'
        },
        {
            img: './img/purple.jpg',
            article: 'Номер 2',
            text: 'Постільна білизна фіолетова',
            sizeL : 'L',
            sizeM : 'M',
            sizeS : 'S',
            priceL : 100,
            priceM: 50,
            priceS: 10 ,
            type : 'set' ,
        },
        {
            img: './img/orange.jpg',
            article: 'Номер 4',
            text: 'Постільна білизна помаранчева',
            sizeL : 'L',
            sizeM : 'M',
            sizeS : 'S',
            priceL : 100,
            priceM: 50,
            priceS: 10 ,
            type : 'fabrics'
        },
        {
            img: './img/orange.jpg',
            article: 'Номер 1',
            text: 'Постільна білизна помаранчева',
            sizeL : 'L',
            sizeM : 'M',
            sizeS : 'S',
            priceL : 100,
            priceM: 50,
            priceS: 10 ,
            type : 'fabrics'
        },
        {
            img: './img/orange.jpg',
            article: 'Номер 2',
            text: 'Постільна білизна помаранчева',
            sizeL : 'L',
            sizeM : 'M',
            sizeS : 'S',
            priceL : 100,
            priceM: 50,
            priceS: 10 ,
            type : 'fabrics' ,
        },
        {
            img: './img/blue.jpg',
            article: 'Номер 4',
            text: 'Постільна білизна синя',
            sizeL : 'L',
            sizeM : 'M',
            sizeS : 'S',
            priceL : 100,
            priceM: 50,
            priceS: 10 ,
            type : 'categorieOne'
        },
        {
            img: './img/blue.jpg',
            article: 'Номер 1',
            text: 'Постільна білизна синя',
            sizeL : 'L',
            sizeM : 'M',
            sizeS : 'S',
            priceL : 100,
            priceM: 50,
            priceS: 10 ,
            type : 'categorieOne'
        },
        {
            img: './img/blue.jpg',
            article: 'Номер 2',
            text: 'Постільна білизна синя',
            sizeL : 'L',
            sizeM : 'M',
            sizeS : 'S',
            priceL : 100,
            priceM: 50,
            priceS: 10 ,
            type : 'categorieOne' ,
        },
        {
            img: './img/pink.jpg',
            article: 'Номер 4',
            text: 'Постільна білизна рожева',
            sizeL : 'L',
            sizeM : 'M',
            sizeS : 'S',
            priceL : 100,
            priceM: 50,
            priceS: 10 ,
            type : 'categorieTwo'
        },
        {
            img: './img/pink.jpg',
            article: 'Номер 1',
            text: 'Постільна білизна рожева',
            sizeL : 'L',
            sizeM : 'M',
            sizeS : 'S',
            priceL : 100,
            priceM: 50,
            priceS: 10 ,
            type : 'categorieTwo'
        },
        {
            img: './img/pink.jpg',
            article: 'Номер 2',
            text: 'Постільна білизна рожева',
            sizeL : 'L',
            sizeM : 'M',
            sizeS : 'S',
            priceL : 100,
            priceM: 50,
            priceS: 10 ,
            type : 'categorieTwo' ,
        },
    ]
}